### ISSUE TITLE
Not working on MacOS or CentOS 

### ISSUE THREAD

**Issue by TryTryAgain** [GorillaStack/dynamodb-csv-export-import#2]
```
Fatal error running CSV transform pipeline:  TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at /usr/local/lib/node_modules/@gorillastack/dynamodb-csv-export-import/index.js:28:28
    at Array.reduce (<anonymous>)
    at transformRecord (/usr/local/lib/node_modules/@gorillastack/dynamodb-csv-export-import/index.js:27:4)
    at DynamoDBCSVRecordTransformer._transform (/usr/local/lib/node_modules/@gorillastack/dynamodb-csv-export-import/index.js:46:27)
    at DynamoDBCSVRecordTransformer.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at DynamoDBCSVRecordTransformer.Writable.write (node:internal/streams/writable:335:10)
    at Parser.ondata (node:internal/streams/readable:777:22)
    at Parser.emit (node:events:390:28)
```

Mac: └❯ node --version
v17.0.0
└❯ npm --version
8.3.0

Linux: node --version
v12.16.1
npm --version
6.11.2

It's the same exact error for both. Maybe the csv format changed?

This is a fake snippet:
```
"snapshot_id","instance_id","purge_time","region","size","start_time","volume_id"
"snap-asfafafasfasfasf","i-0asfjafhjasfasfbbb","2022-03-14 15:31:41.303704","ap-southeast-1","100","2021-12-14 15:31:41.303704","vol-08jasfjf77hsafj"
```

**Comment by endymion** [comment]
I see the same issue.

**Comment by ManuelSch** [comment]
+1
